spring:
  config:
    import:
      privacy.yml
  application:
    name:
      naem
  datasource:
    url: jdbc:mysql://${db.host}:${db.port}/${db.database}?serverTimeZone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${db.username}
    password: ${db.password}
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: false
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true

logging:
  level:
    com.app: debug

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

jwt:
  secret: ${jwt.secret}

kakao:
  client:
    id: ${client.id}
    secret: ${client.secret}