spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${HOST}:${PORT}/${DATABASE_NAME}?${OPTIONS}
    username: ${USER_NAME}
    password: ${USER_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true
    open-in-view: true
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    
logging:
  level:
    com.app: debug

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

jwt:
  secret: ${jwt.secret}

kakao:
  client:
    id: ${client.id}
    secret: ${client.secret}
